services:
  api:
    build:
      context: .
      dockerfile: backend/MjmlEditor.Api/Dockerfile.dev
    container_name: mjml-editor-api-dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDb__ConnectionString: mongodb://mongo:27017
      MongoDb__DatabaseName: mjml-editor-dev
      Serilog__WriteTo__1__Args__serverUrl: http://seq:5341
      Cors__AllowedOrigins__0: http://localhost:5173
      Cors__AllowedOrigins__1: http://127.0.0.1:5173
      R2__AccountId: "ade7b4962ee6e1aa6a41a5638849ac1f"
      R2__BucketName: "mjml-editor-media"
      R2__AccessKeyId: "218980f8d53d684e5b4606a84ad79a11"
      R2__SecretAccessKey: "9e038c5d4cbf261e29913198c48b2ddc4dae64ce51035d8affb6bac90fb7b41e"
      R2__PublicBaseUrl: "https://pub-83d2048d82314d999e0f7ada3080a553.r2.dev"
    ports:
      - "5261:8080"
    volumes:
      - .:/workspace
      - dotnet-nuget:/root/.nuget/packages
    depends_on:
      mongo:
        condition: service_started
      seq:
        condition: service_started

  frontend:
    build:
      context: ./frontend/mjml-editor-ui
      dockerfile: Dockerfile.dev
    container_name: mjml-editor-ui-dev
    environment:
      VITE_API_BASE_URL: http://localhost:5261
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/mjml-editor-ui:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      api:
        condition: service_started

  mongo:
    image: mongo:8.0
    container_name: mjml-editor-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  seq:
    image: datalust/seq:latest
    container_name: mjml-editor-seq-dev
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - seq-data:/data

volumes:
  dotnet-nuget:
  frontend-node-modules:
  mongo-data:
  seq-data:
